### ISSUE TITLE
[15] Stworzyć poprawną stronę główną 

### ISSUE THREAD

**Issue by hawkerpl** [MM-PITE/first_project#10]
* Rezygnujemy z navbara w formie obecnej 
* opcje responses i create form zastępujemy stroną główną, na której będzie tabelka z formularzami i liczbą odpowiedzi
* klik w nazwe formularza będzie przenosił do strony ze szczegółami odpowiedzi
* na stronie głównej będzie się znajdować też przycisk (create new form)
* w navbarze zostaje możliwośc przejścia do strony głównej, lub do ustawień użytkownika

Ważna zmiana, wołam o zatwierdzenie @tripletime  @Tomo2

**Comment by tripletime** [comment]
@hawkerpl zgadzam się :+1:

**Comment by hawkerpl** [comment]
@tripletime  o co chodzi :P ?

**Comment by tripletime** [comment]
@hawkerpl 
linki w navbarze dalej nie działają

logout
ustawienia uzytkownika
