### ISSUE TITLE
[10] Status ogłoszenia jest źle zapisywany / odczytywany

### ISSUE THREAD

**Issue by tripletime** [MM-PITE/first_project#11]
Należy sprawdzić przede wszystkim plik views.py w create_form (@hawkerpl)

**Comment by hawkerpl** [comment]
@tripletime ten wpis w ogóle mi nic nie mówi

**Comment by tripletime** [comment]
@hawkerpl Zauwazylem ze nie działa, opisałem Ci wszystko przez telefon, chciales issue to jest, gdybym to ja zajał się sprawdzaniem gdzie nie działa to bym podpiął issue pod siebie ;P

**Comment by hawkerpl** [comment]
@tripletime ale opisz co rozumiesz przez "źle zapisywany/odczytywany"

**Comment by tripletime** [comment]
@hawkerpl ehhh trzeba było słuchać jak nawijałem o tym :)

Zrób sobie nowego użytkownika, dodaj nim 2 formularze
Pierwszy ze statusem Open, drugi ze statusem Close.

potem przejdź pod te linki, które się generują żeby się zapisywać na ogłoszenia i spróboj się zarejestrować na nie.

**Comment by hawkerpl** [comment]
@tripletime chodzi ci o brak informacji o tym czy jest open czy close w miejscu gdzie mozna się rejestrować, czy o to że ten formularz w ogóle nei powinien się wyświetlać ?

**Comment by tripletime** [comment]
@MM-PITE/owners kontynuacja wątku na gitterze

**Comment by hawkerpl** [comment]
u mnie działa ( w sensie nie widze opisanego problemu, ale może to po commicie )

**Comment by tripletime** [comment]
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
...
działa
