### ISSUE TITLE
[30] wprowadzić ujednolicony system autoryzacji

### ISSUE THREAD

**Issue by hawkerpl** [MM-PITE/first_project#14]
W wielu miejscach musimy sprawdzać czy użytkownik jest zalagowoany poprawnie, musimy ujednolicić wiadomość o błędzie z powodu braku autoryzacji (widoki i może templaty), jak i doskrobać testy w odpowiednich modułach

**Comment by hawkerpl** [comment]
@tripletime dzisiaj na mpf dogadamy jeszcze

**Comment by tripletime** [comment]
@hawkerpl o shit nie zauważyłem że na mpf mieliśmy coś dogadywać, a po mpf nic nie wspominałeś ;)

**Comment by tripletime** [comment]
9.06 23:59:59

**Comment by tripletime** [comment]
@hawkerpl
co ma się wyświetlać / jaki komunikat / czy strona główna?  jeśli niezalogowany użytkownik próbuje coś zrobić czego nie powinien?

jakie testy mam dopisać do autoryzacji użytkownika, którego funkcje autoryzacji i wylogowania po prostu są w django? eem

**Comment by hawkerpl** [comment]
@tripletime  to co ma się wyświetlać zależy od ciebie, możesz zrobić taki template komunikatu któremu będzie można dodać opis lub użyć domyślnego, i któy będzie można używać w każdym appie

a co do testów to nie testuj tego co zrobiła django, tylko testuj użycie komponentów djangowych (w sensie modelu django nie musisz testować)

**Comment by hawkerpl** [comment]
@tripletime also zrób to proszę razem z #12
