### ISSUE TITLE
[15] Zmienić layout create_form/ na ładniejszy (nie jedno pole z tekstem za drugim)

### ISSUE THREAD

**Issue by tripletime** [MM-PITE/first_project#18]
ujednolicenie z dużo ładniejszym, a już gotowym layoutem form_response/

**Comment by tripletime** [comment]
@hawkerpl podpinam pod siebie bo już to robiłem, jak się podoba pomysł?

**Comment by hawkerpl** [comment]
@tripletime zależy jak dokładniej, akurat przy wypełnianiu pól to może być przydatne że jest jedno pod drugim

**Comment by tripletime** [comment]
@hawkerpl miałem na myśli to, że pola takie jak cena czy max participants oraz start i end date nie muszą zajmować całej szerokości strony -> start dałbym obok end i te inty razem. Teraz kiedy ta stronka faktycznie może przyjąć 10 giftów i 10 small eventów i 10 plików i jeszcze 10 zdefiniowanych pól potrafi zrobić się naaaprawdę długa

**Comment by hawkerpl** [comment]
:+1: approved
