### ISSUE TITLE
[15] Zmienić layout form_response/ na ładniejszy (nie jedno pole z tekstem za drugim)

### ISSUE THREAD

**Issue by hawkerpl** [MM-PITE/first_project#2]

**Comment by tripletime** [comment]
jako że sam poprawiałem form_response i wydawało mi się że już jest ładniej niż było to podrzuć jakiś link czy stronkę, które pokaże co konkretnie masz na myśli

**Comment by hawkerpl** [comment]
@tripletime 
##teraz jest tak:
__Jaka waga:__
15
__O co chodzi__:
o to
__dlaczego__: 
bo tak
__cena:__
15
__nazwa:__
zawartość
__nazwa:__
zawartość
__nazwa:__
zawartość
__nazwa:__
zawartość
__nazwa:__
zawartość
__nazwa:__
zawartość

##Jak ja to widze
__Jaka waga__:15, __nazwa:__ krótka zawartość, __nazwa:__ krótka zawartość,
__długa zawartość__:Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce iaculis, elit non luctus porta, risus sem lacinia nisi, ac sagittis ipsum arcu sit amet sapien. Nullam blandit facilisis nisl. Nulla facilisi. Pellentesque fringilla tortor rhoncus enim posuere vulputate. Vestibulum at gravida elit, eu sodales tortor. Nulla ac diam vel diam congue dapibus.
__nazwa:__ jakastam  inn krótka zawartość,, __nazwa:__ krótka zawartość,


które ci się wydaje czytelniejsze i ładniejsze ?

**Comment by tripletime** [comment]
wszystko jasne :+1:

**Comment by hawkerpl** [comment]
##29.05 18.00 deadline

**Comment by tripletime** [comment]
@hawkerpl robiąc dokładnie tak jak napisałeś:
**Jaka waga:**15, **nazwa:** krótka zawartość, **nazwa:** krótka zawartość, ...
strasznie się to rozjechało, zrobiłem więc tak, że nazwy pól formularza znajdują się nad nimi, tak wygląda dużo lepiej
