### ISSUE TITLE
[30] Dodanie funkcjonalności response list

### ISSUE THREAD

**Issue by hawkerpl** [MM-PITE/first_project#21]
należy dodać:
* zmianę statusu eventu
* usuwanie osób z rezerwacji
* wyświetlanie szczegółowych odpowiedzi

**Comment by tripletime** [comment]
@hawkerpl 
wyświetlania szczegółowych odpowiedzi nie zrobię, dopóki nie będzie się dało w zgłoszeniu na event wpisać tych szczegółowych danych.

@Tomo2 
kiedy mniejwięcej będziesz robił #19 ?

**Comment by Tomo2** [comment]
W weekend. Wcześniej nie mam jak bo egzaminy, praca i seminarkę na AOiS muszę zrobić. W sobotę to zrobię.

**Comment by tripletime** [comment]
@hawkerpl wołam czy mógłbyś dokończyć wyświetlanie szczegółowych odpowiedzi?
