### ISSUE TITLE
[15] Coś jest nie tak z typeHelper w form_response

### ISSUE THREAD

**Issue by hawkerpl** [MM-PITE/first_project#25]
https://github.com/MM-PITE/first_project/blob/master/form_response/typeHelper.py#L8

Próbowałem napisać testy do tego, nie wiem co jest nie tak, ale wygląda na to że ta funkcja nawet nie jest używana. @Tomo2  albo popraw to sam albo napisz ocb. 

Edit: to w ogóle nie działa, w sensie dodawanie własnych pól. Wołam w takim razie też @tripletime

**Comment by Tomo2** [comment]
Hmm... no więc w przypadku pól, których typ wyciągamy z DB muszę wiedzieć jaki typ ma być w formularzu i do tej konwersji ta metoda służy. Jest używana w tej metodzie, za którą mnie opierniczyłeś (btw. można tu rzucać łaciną podwórkową czy jesteśmy monitorowani :D?) tj. index w form_response/views. Jak chcesz to mogę skrobnąć testy do niej. Tylko nie wiem czy do niedzieli zdążę.

**Comment by tripletime** [comment]
@MM-PITE/owners jeśli obsługa typu miała by działać tak jak jest w tym kodzie, to lepiej gdyby na formularzu był jakiś dropdown zamiast input texta
