### ISSUE TITLE
[40] Poprawić widok w którym następuje zapisanie pól do wypełnienia do bazy.

### ISSUE THREAD

**Issue by hawkerpl** [MM-PITE/first_project#4]
* Dodać obsługe "dynamicznych" pól
* Poprawić ich parsowanie

**Comment by tripletime** [comment]
"dynamiczne pola" zostają w obecnej formie?
czy masz jakiś pomysł co zrobić z plikami? one są zrobione dynamicznie bez ""

**Comment by hawkerpl** [comment]
@tripletime myśle że na razie tak, zostają w obecnej.
Nie nie mam pojęcia co robić z plikami.

**Comment by hawkerpl** [comment]
02.06 23:59

**Comment by tripletime** [comment]
@MM-PITE/owners 
stan na: 2.06 23:59:59

Chwilowo pozostaje otwarte. Ze wszystkich pól problemem okazały się pliki. Z tego co udało mi się już wyczytać
[TU](https://docs.djangoproject.com/en/1.7/topics/http/file-uploads/)
[ORAZ TU](https://docs.djangoproject.com/en/1.7/ref/forms/fields/#django.forms.FileField)
to żeby to zrobić tak jak powinno być potrzeba zmienić nieco ERD i model.

**Comment by tripletime** [comment]
hmmm, gdyby potraktować opis dosłownie :D to wszystkie "dynamicznie" tworzone pola są ok, tylko te prawdziwie dynamiczne są nie ok :D to closować? xD

**Comment by hawkerpl** [comment]
zostaw otwarte, zrób commit i push z tym co już masz na swój branch (ważne - test muszą przechodzić i dodaj jeszcze w nazwie commita numer tego issue z kratką, wiesz ocb) jeżeli będzie 80%, a z tego co mówisz to bedzie, to dokończ w najbliższym czasie i wtedy zamkniemy.

**Comment by tripletime** [comment]
@hawkerpl wrzuciłem bez files - a potem jeszcze zmodyfikowalem tested_form_dict w testach, żeby był zgodny z obowiązującym od wczoraj :)

tam jest takie coś fajnego jak request:FILES
co robić z plikami? przerabiać model i erd?

**Comment by hawkerpl** [comment]
ustalone:
* do bazy danych dopisujemy tak żeby można było wpisać link i opis
* pliki przyjmujemy tylko jako linki do zewnętrznych serwisów

**Comment by tripletime** [comment]
od tej pory będzie to wyglądać tak, już sprawdzam czy teraz dużo testów się psuje

class Files(models.Model):
    file_link = models.CharField(max_length=120)
    file_description = models.CharField(max_length=120)
    event = models.ForeignKey(Event)
